"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from enum import IntEnum
from corsheaders.defaults import default_headers
from appstoreserverlibrary.models.Environment import Environment
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-89!61+kh28w$wwsy-d*9=8h^#8um&)jynj5w74gsy(bvju=7!p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv("CSRF_TRUSTED_ORIGINS").split(",")]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'storages',

    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'health_check.contrib.celery',
    'health_check.contrib.redis',

    'modeltranslation',

    'user',
    'ability',
    'brand',
    'subscription',
    'news',
    'premium',
    'notifications',
    'technical_support',
    'deep_link_open',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'backend.middlewares.LogResponsesMiddleware',
]

ROOT_URLCONF = 'backend.urls'
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'real-ip',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'bazhay'),
        'USER': os.getenv('POSTGRES_USER', 'bazhay'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'qwerty123'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'TEST': {
            'NAME': 'test_bazhay',
        },
    }
}


class RedisDatabases(IntEnum):
    DEFAULT: int = 0
    CELERY: int = 1
    CELERY_RESULTS: int = 2
    LOGIN_CODE: int = 3
    IP_CONTROL: int = 4
    LOCK: int = 5
    CACHE: int = 6


REDIS_HOST = os.environ.get('REDIS_HOST', 'redis')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD') or None
REDIS_USE_SSL = os.environ.get('REDIS_USE_SSL', '').upper() in ('TRUE', '1', 'Y', 'YES', 'T')

REDIS_PROTOCOL = 'rediss' if REDIS_USE_SSL else 'redis'
REDIS_AUTH = f'default:{REDIS_PASSWORD}@' if REDIS_PASSWORD else ''

REDIS_CONNECTION = {
    'host': REDIS_HOST,
    'port': REDIS_PORT,
    'password': REDIS_PASSWORD,
}

REDIS_CONNECTION_QUERY = '?ssl_cert_reqs=none' if REDIS_USE_SSL else ''
REDIS_CONNECTION_STRING = '{protocol}://{auth}{host}:{port}/%s{query}'.format(
    protocol=REDIS_PROTOCOL,
    auth=REDIS_AUTH,
    **REDIS_CONNECTION,
    query=REDIS_CONNECTION_QUERY,
)

CELERY_TIMEZONE = "Europe/Kiev"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_URL = REDIS_CONNECTION_STRING % int(RedisDatabases.CELERY)
CELERY_RESULT_BACKEND = REDIS_CONNECTION_STRING % int(RedisDatabases.CELERY_RESULTS)



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
DEFAULT_FILE_STORAGE = 'backend.storages.CustomS3Boto3Storage'

AWS_MEDIA_CONVERT_ENDPOINT = os.getenv('AWS_MEDIA_CONVERT_ENDPOINT')
AWS_MEDIA_CONVERT_ROLE = os.getenv('AWS_MEDIA_CONVERT_ROLE')

AWS_CLOUDWATCH_LOG_GROUP = "django-logs"

import boto3

boto3.setup_default_session(region_name=AWS_S3_REGION_NAME)


MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{int(RedisDatabases.CACHE)}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'backend.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 1))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 120))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'user.BazhayUser'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


LANGUAGES = (
    ('uk', 'Ukrainian'),
    ('en', 'English'),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [
                {
                    "address": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0",
                    "password": f"{REDIS_PASSWORD}",
                }
            ],
        },
    },
}

APPLE_KEY_ID = os.getenv("APPLE_KEY_ID")
APPLE_ISSUER_ID = os.getenv("APPLE_ISSUER_ID")
APPLE_BUNDLE_ID = os.getenv("APPLE_BUNDLE_ID")
APPLE_ENVIRONMENT = Environment.SANDBOX


TIME_LIFE_OTP_CODE = int(os.getenv('TIME_LIFE_OTP_CODE', 60 * 10))

SIGHTENGINE_API_USER = os.getenv('VALIDATE_API_USER')
SIGHTENGINE_API_SECRET = os.getenv('VALIDATE_API_SECRET')
SIGHTENGINE_VALIDATE_MODEL = 'nudity-2.1,weapon,recreational_drug,medical,gore-2.0,offensive,self-harm,violence'
SIGHTENGINE_PHOTO_LINK = 'https://api.sightengine.com/1.0/check.json'
SIGHTENGINE_VIDEO_LINK = 'https://api.sightengine.com/1.0/video/check-sync.json'
SIGHTENGINE_VALIDATE_FIELDS = ["sexual_activity", "sexual_display", "erotica", "very_revealing", "male_chest",
                               "slightly_revealing", "visibly_undressed", "firearm", "knife", "aiming_threat",
                               "aiming_safe", "in_hand_not_aiming", "worn_not_in_hand", "not_worn", "recreational_drug",
                               "cannabis", "cannabis_drug", "gore", "very_bloody", "slightly_bloody", "corpse",
                               "serious_injury", "superficial_injury", "offensive", "nazi", "supremacist", "terrorist",
                               "self-harm", "violence", "physical_violence", "firearm_threat"]


# Content acceptance threshold. If this value is higher than this, the content will not be allowed. From 0 to 1
VALIDATE_THRESHOLD = 0.5

APP_STORE_LINK=os.getenv('APP_STORE_LINK')
APPLE_REDIRECT_FILE_PATH = "deep_link_open/templates/apple_redirect.json"

PLAY_STORE_LINK=os.getenv('PLAY_STORE_LINK')
PLAY_STORE_FILE_PATH = "deep_link_open/templates/assetlinks.json"


GPT_MODEL = os.getenv('GPT_MODEL')
GPT_API_KEY = os.getenv('GPT_API_KEY')
GPT_API_MODEL = 'https://api.openai.com/v1/chat/completions'

CACHES_TIME = 60 * 60 * 1

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'rest_framework': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'redis': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

WISH_WITHOUT_PREMIUM = int(os.getenv('WISH_WITHOUT_PREMIUM'))

CELERY_BEAT_SCHEDULE = {
    'check-birthdays-daily': {
        'task': 'user.tasks.check_birthdays_and_notify',
        'schedule': crontab(hour=str(os.getenv('SEND_NOTIFICATION_BIRTHDAY_HOUR', '12')), minute="29"),
    },
    'send-congratulatory-notification': {
        'task': 'notifications.tasks.send_congratulatory_notification',
        'schedule': crontab(minute='*'),
    },
    'deactivate-inactive-chats': {
        'task': 'technical_support.tasks.deactivate_inactive_chats',
        'schedule': crontab(minute='*/2'),
    },
    'delete_guest_user': {
        'task': 'user.tasks.delete_guest_user',
        'schedule': crontab(hour='12'),
    },
    'health-check-every-5-minutes': {
        'task': 'health_checkers.tasks.scheduled_health_check',
        'schedule': crontab(minute='*/5'),
    },
}

DOWNLOAD_PHOTO_TIMEOUT = int(os.getenv('DOWNLOAD_PHOTO_TIMEOUT', 3))

TIME_LIFE_CHAT = int(os.getenv('TIME_LIFE_CHAT', 10))

REDIS_URL = REDIS_CONNECTION_STRING % int(RedisDatabases.DEFAULT)

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
